apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/llama-server
  - ../../base/chainlit-app
patches:
  - path: llama-server-patch.yaml
  - path: chainlit-app-patch.yaml
